### ISSUE TITLE
Pull down bank statements hang on plaintext response

### ISSUE THREAD

**Issue by Vitexus** [Spoje-NET/php-abraflexi#24]
`
"/usr/bin/php" "/home/vitex/Projects/EASE/abraflexi-matcher/src/StahniBanku.php"
10/12/21 23:49:30 •AbraFlexi\Banka‣  ⚙ StahniBanku PHP v7.4.24 EasePHP Framework v0.5 ServerURL https://admin@flexibee-dev.spoje.net:5434/c/vitex_software/banka library v2.6 (AbraFlexi 2021.7.6)
10/12/21 23:49:31 •AbraFlexi\Banka‣  ⚙ Download online bank statements
10/12/21 23:51:07 •Ease\Molecule‣  ☠ AbraFlexi\Banka: JSON Decoder: Syntax error
PHP Fatal error:  Uncaught AbraFlexi\Exception: AbraFlexi\Banka: JSON Decoder: Syntax error in /home/vitex/Projects/EASE/abraflexi-matcher/vendor/spojenet/flexibee/src/AbraFlexi/RO.php:1072
Stack trace:
#0 /home/vitex/Projects/EASE/abraflexi-matcher/vendor/spojenet/flexibee/src/AbraFlexi/RO.php(966): AbraFlexi\RO->rawJsonToArray('Soubor 2021-10-...')
#1 /home/vitex/Projects/EASE/abraflexi-matcher/vendor/spojenet/flexibee/src/AbraFlexi/RO.php(950): AbraFlexi\RO->rawResponseToArray('Soubor 2021-10-...', 'json')
#2 /home/vitex/Projects/EASE/abraflexi-matcher/vendor/spojenet/flexibee/src/AbraFlexi/Banka.php(43): AbraFlexi\RO->performRequest('nacteni-vypisu-...', 'PUT', 'txt')
#3 /home/vitex/Projects/EASE/abraflexi-matcher/src/StahniBanku.php(21): AbraFlexi\Banka->stahnoutVypisyOnline()
#4 {main}
  thrown in /home/vitex/Projects/EASE/abraflexi-matcher/vendor/spojenet/flexibee/src/AbraFlexi/RO.php on line 1072

Fatal error: Uncaught AbraFlexi\Exception: AbraFlexi\Banka: JSON Decoder: Syntax error in /home/vitex/Projects/EASE/abraflexi-matcher/vendor/spojenet/flexibee/src/AbraFlexi/RO.php on line 1072

AbraFlexi\Exception: AbraFlexi\Banka: JSON Decoder: Syntax error in /home/vitex/Projects/EASE/abraflexi-matcher/vendor/spojenet/flexibee/src/AbraFlexi/RO.php on line 1072

Call Stack:
    0.1177     400880   1. {main}() /home/vitex/Projects/EASE/abraflexi-matcher/src/StahniBanku.php:0
    9.8523    1817880   2. AbraFlexi\Banka->stahnoutVypisyOnline() /home/vitex/Projects/EASE/abraflexi-matcher/src/StahniBanku.php:21
    9.8523    1817880   3. AbraFlexi\Banka->performRequest($urlSuffix = 'nacteni-vypisu-online.json', $method = 'PUT', $format = 'txt') /home/vitex/Projects/EASE/abraflexi-matcher/vendor/spojenet/flexibee/src/AbraFlexi/Banka.php:43
   16.9741    2037608   4. AbraFlexi\Banka->rawResponseToArray($responseRaw = 'Soubor 2021-10-12 214932_2601221676-2010_CZK.gpc\n   Výpis 0 pro účet 0000000 - Načítání proběhlo úspěšně. The loaded statement does not contain any item. Počet položek 0\n\nSoubor 2021-10-12 214932_CZ.gpc\n   Výpis 0 pro účet 000000 - Načítání proběhlo úspěšně. The loaded statement does not contain any item. Počet položek 0\n\n', $format = 'json') /home/vitex/Projects/EASE/abraflexi-matcher/vendor/spojenet/flexibee/src/AbraFlexi/RO.php:950
  105.2005    2037608   5. AbraFlexi\Banka->rawJsonToArray($rawJson = 'Soubor 2021-10-12 60104.gpc\n   Výpis 0 pro účet 000000-2601221676 - Načítání proběhlo úspěšně. The loaded statement does not contain any item. Počet položek 0\n\nSoubor 2021-10-12 214932.gpc\n   Výpis 0 pro účet 000000-2800677051 - Načítání proběhlo úspěšně. The loaded statement does not contain any item. Počet položek 0\n\n') /home/vitex/Projects/EASE/abraflexi-matcher/vendor/spojenet/flexibee/src/AbraFlexi/RO.php:966
`

**Comment by Vitexus** [comment]
Hotfixed.
