### ISSUE TITLE
Unparsed error

### ISSUE THREAD

**Issue by Vitexus** [Spoje-NET/php-abraflexi#37]
```
01/17/2024 10:17:2 💀 ❲AbraFlexi StahniBanku⦒AbraFlexi\\Banka❳ Unparsed error: {\"winstrom\":{\"@version\":\"1.0\",\"success\":\"false\",\"stats\":{\"created\":\"0\",\"updated\":\"0\",\"deleted\":\"0\",\"skipped\":\"1\",\"failed\":\"1\"},\"results\":[{\"code\":\"Výpis 0 pro účet 2900886213/2010 -  Počet položek 0\",\"errors\":[{\"message\":\"Během stahování výpisu pro účet EURO FIO (2900886213/2010) došlo k chybě.\\nNedodržujete minimální interval 30 sekund mezi dotazy na daný token (bez ohledu na typ formátu).\"}]},{\"code\":\"Výpis 0 pro účet 2800061687 -  Počet položek 0\",\"infos\":[{\"message\":\"Načítání proběhlo úspěšně. Načtený výpis neobsahuje žádnou položku.\"}]}]}}01/17/2024 10:17:2 💀 ❲AbraFlexi StahniBanku⦒AbraFlexi\\RO::parseResponse:124❳ AbraFlexi\\Banka: Problem PHP Fatal error:  Uncaught AbraFlexi\\Exception: AbraFlexi\\Banka: Problem  in /usr/share/php/AbraFlexi/RO.php:1234
Stack trace:
#0 /usr/share/php/AbraFlexi/RW.php(124): AbraFlexi\\RO->parseResponse()
#1 /usr/share/php/AbraFlexi/RO.php(1001): AbraFlexi\\RW->parseResponse()
#2 /usr/share/php/AbraFlexi/Banka.php(55): AbraFlexi\\RO->performRequest()
#3 /usr/lib/abraflexi-matcher/StahniBanku.php(22): AbraFlexi\\Banka->stahnoutVypisyOnline()
#4 {main}
  thrown in /usr/share/php/AbraFlexi/RO.php on line 1234
```

```json
{
  "winstrom": {
    "@version": "1.0",
    "success": "false",
    "stats": {
      "created": "0",
      "updated": "0",
      "deleted": "0",
      "skipped": "1",
      "failed": "1"
    },
    "results": [
      {
        "code": "Výpis 0 pro účet 2900886213/2010 -  Počet položek 0",
        "errors": [
          {
            "message": "Během stahování výpisu pro účet EURO FIO (2900886213/2010) došlo k chybě.\nNedodržujete minimální interval 30 sekund mezi dotazy na daný token (bez ohledu na typ formátu)."
          }
        ]
      },
      {
        "code": "Výpis 0 pro účet 2800061687 -  Počet položek 0",
        "infos": [
          {
            "message": "Načítání proběhlo úspěšně. Načtený výpis neobsahuje žádnou položku."
          }
        ]
      }
    ]
  }
}
```

**Comment by Vitexus** [comment]
Error handling updated
